---
title: "Warehouse quality control"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(scales)
library(shiny)
```

## Plot supplier risk

```{r, echo=FALSE}
inputPanel(
  selectInput("sup_n_values", label = "Sample size:",
              choices = seq(500, 1000, by = 100), selected = 100,width = '600px'),
  selectInput("sup_c_values", label = "Acceptance criterion:",
              choices = seq(0,70,by= 10), selected = 50,width = '600px')
)

p_values <- seq(0.01,0.2,by=0.01)
sup_results <- reactive({
  expand_grid(n = input$sup_n_values, c = input$sup_c_values, p = p_values) %>%
    mutate(n=as.numeric(n),c = as.numeric(c))%>%
    mutate(prob_accept = pbinom(c,n,p)) %>% 
   mutate(supplier_risk = round(1-prob_accept,2),
         reciever_risk = round(prob_accept,2))
})


output$supplier_risk <- renderPlot({
  sup_results() %>% 
    ggplot(aes(x = p, y = supplier_risk, color = factor(n))) +
    geom_line(size = 1.1,alpha = 0.5) +
    geom_point()+
    geom_text(aes(label = supplier_risk),vjust = -1)+
    scale_y_continuous(labels = scales::percent)+
    scale_x_continuous(labels = scales::percent)+
    theme_minimal()+
    theme(legend.position = "None",
          plot.title = element_text(size = 25),
          axis.text = element_text(size = 15))+
    labs(title = "Supplier risk - Type1 error, for different defect rates p",
         x = "Defect rate", y = "Supplier risk")
})

plotOutput("supplier_risk")
br()
br()

```

## Plot warehouse risk

```{r}

inputPanel(
  selectInput("wh_n_values", label = "Sample size:",
              choices = seq(500, 1000, by = 100), selected = 100),
  selectInput("wh_c_values", label = "Acceptance criterion:",
              choices = seq(0,70,by= 10), selected = 50),
)

wh_results <- reactive({
  expand_grid(n = input$wh_n_values, c = input$wh_c_values, p = p_values) %>%
    mutate(n=as.numeric(n),c = as.numeric(c))%>%
    mutate(prob_accept = pbinom(c,n,p)) %>% 
    mutate(supplier_risk = round(1-prob_accept,2),
         reciever_risk = round(prob_accept,2))
})


output$warehouse_risk <- renderPlot({
  wh_results() %>%
    ggplot(aes(x = p, y = reciever_risk,color= factor(n))) +
    geom_line(size = 1.1,alpha = 0.5) +
    geom_point()+
    geom_text(aes(label = reciever_risk),vjust = -1)+
    scale_y_continuous(labels = scales::percent)+
    scale_x_continuous(labels = scales::percent)+
    theme_minimal()+
    theme(legend.position = "None",
          plot.title = element_text(size = 25),
          axis.text = element_text(size = 15))+
    labs(title = "Warehouse risk - Type2 error, for different defect rates p",
         x = "Defect rate", y = "Warehouse risk")
})

plotOutput("warehouse_risk")


```
